runtime: python27
api_version: 1
threadsafe: true
service: web-app

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /static
  static_dir: static

- url: /.*
  script: main.app

error_handlers:
- file: templates/error_default.html

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
